#!/usr/bin/env bash

set -e

#--------------------------------------------------------------
# functions
#--------------------------------------------------------------
error() {
  >&2 echo "ERROR: $@"
  exit 1
}

#--------------------------------------------------------------
# execution
#--------------------------------------------------------------
[ -d output/bin ] || error "output/bin does not exist"

cp -rf ./input ./output/bin
cd ./output/bin
./run +UVM_VERBOSITY=UVM_HIGH $@
