#!/usr/bin/env bash

set -e

#--------------------------------------------------------------
# functions
#--------------------------------------------------------------
error() {
  >&2 echo "ERROR: $@"
  exit 1
}

run_ius(){
  [ -f generated_tb/sim/compile_ius.sh ] || error "generated_tb/tb/compile_ius.sh does not exist"
  cd generated_tb/sim
  ./compile_ius.sh -access +rw +UVM_VERBOSITY=UVM_HIGH -q $@
}

run_questa(){
  [ -f generated_tb/sim/run_questa ] || error "generated_tb/tb/run_questa does not exist"
  cd generated_tb/sim
  ./run_questa +UVM_VERBOSITY=UVM_HIGH $@
}

#--------------------------------------------------------------
# execution
#--------------------------------------------------------------
case "$1" in
  "-ius")
    shift
    run_ius $@
    ;;
  "-questa")
    shift
    run_questa $@
    ;;
  *)
    error "Unknown simulator: $1"
    ;;
esac
