#!/usr/bin/env bash

set -e

IUS_HOME=$(ncroot)
TOP_DIR="../riscv-simple-sv"

RTL_DIR="$TOP_DIR/core"
TEST_DIR="$TOP_DIR/tests"
TB_DIR="$TOP_DIR/testbench"


#--------------------------------------------------------------
# functions
#--------------------------------------------------------------
error() {
  >&2 echo "ERROR: $@"
  exit 1
}

mkdir -p output
cd output

test_name="$1"
[ "$test_name" == "" ] && test_name="toto"

make -C $TEST_DIR

xrun -q                                               \
  -vtimescale 1ns/1ps                                 \
  -uvmhome ${IUS_HOME}/tools/methodology/UVM/CDNS-1.2 \
  -access +rw                                         \
  +incdir+../tb/include                               \
  +incdir+../tb/uvm_server/sv                         \
  +incdir+../tb/top/sv                                \
  +incdir+../tb/top_test/sv                           \
  +incdir+../tb/top_tb/sv                             \
  -incdir $TB_DIR                                     \
  -incdir $RTL_DIR/common/                            \
  -incdir $RTL_DIR/singlecycle/                       \
  $RTL_DIR/common/*                                   \
  $RTL_DIR/singlecycle/*                              \
  +text_file=$TEST_DIR/$test_name.text.vh             \
  +data_file=$TEST_DIR/$test_name.data.vh             \
  ../tb/uvm_server/sv/uvm_server_pkg.sv               \
  ../tb/uvm_server/sv/uvm_server_if.sv                \
  ../tb/top/sv/top_pkg.sv                             \
  ../tb/top_test/sv/top_test_pkg.sv                   \
  ../tb/top_tb/sv/top_th.sv                           \
  ../tb/top_tb/sv/top_tb.sv                           \
  +UVM_TESTNAME=top_test
